const date=[{
    "_id":"pokemon_001",
    "name":"Bulbasaur",
    "image":"https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
    "hp":100,
    "pp":10,
    "moves":[{
        "name":"Vine Whip",
        "damage":15,
        "pp":2
    },
    {
        "name":"Tackle",
        "damage":10,
        "pp":1
    },
    {
        "name":"Rest",
        "damage":0,
        "pp":-3
    },
]

},
{
    "_id":"pokemon_004",
    "name":"Charmender",
    "image":"https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
    "hp":100,
    "pp":10,
    "moves":[{
        "name":"Bite",
        "damage":25,
        "pp":2
    },
    {
        "name":"Ember",
        "damage":20,
        "pp":1
    },
    {
        "name":"Rest",
        "damage":0,
        "pp":-3
    },
]

},
{
    "_id":"pokemon_143",
    "name":"Snorlax",
    "image":"https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png",
    "hp":100,
    "pp":10,
    "moves":[{
        "name":"sleep",
        "damage":1,
        "pp":1
    },
    {
        "name":"Rock Slide",
        "damage":40,
        "pp":4
    },
    {
        "name":"Rest",
        "damage":0,
        "pp":-3
    },
]

},
{
    "_id":"pokemon_007",
    "name":"Squirtle",
    "image":"https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
    "hp":100,
    "pp":10,
    "moves":[{
        "name":"Bubble Beam",
        "damage":25,
        "pp":3
    },
    {
        "name":"Skull Bash",
        "damage":30,
        "pp":4
    },
    {
        "name":"Rest",
        "damage":0,
        "pp":-3
    },
]

},
{
    "_id":"pokemon_025",
    "name":"Pikachu",
    "image":"https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    "hp":100,
    "pp":10,
    "moves":[{
        "name":"Spark",
        "damage":15,
        "pp":3
    },
    {
        "name":"Wild Charge",
        "damage":25,
        "pp":4
    },
    {
        "name":"Rest",
        "damage":0,
        "pp":-3
    },
]

},
{
    "_id":"pokemon_052",
    "name":"Meowth",
    "image":"https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png",
    "hp":110,
    "pp":10,
    "moves":[{
        "name":"Cut",
        "damage":10,
        "pp":2
    },
    {
        "name":"Bite",
        "damage":20,
        "pp":4
    },
    {
        "name":"Rest",
        "damage":0,
        "pp":-3
    },
]

},
{
    "_id":"pokemon_258",
    "name":"Mudkip",
    "image":"https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/258.png",
    "hp":120,
    "pp":10,
    "moves":[{
        "name":"Iron Tail",
        "damage":20,
        "pp":3
    },
    {
        "name":"Waterfall",
        "damage":30,
        "pp":6
    },
    {
        "name":"Rest",
        "damage":0,
        "pp":-3
    },
]

},
{
    "_id":"pokemon_133",
    "name":"Eevee",
    "image":"https://raw.githubusercontent.com/pokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png",
    "hp":125,
    "pp":12,
    "moves":[{
        "name":"Headbutt",
        "damage":30,
        "pp":3
    },
    {
        "name":"Tail Whip",
        "damage":15,
        "pp":4
    },
    {
        "name":"Rest",
        "damage":0,
        "pp":-3
    },
]

}]